### ISSUE TITLE
Where is the Arduino code?

### ISSUE THREAD

**Issue by thomasfromla** [rlisle/Alexa#1]
It looks like there is just some placeholder code here in github.  Can you post your updated Arduino code? I'm not sure how Alexa's js code calls the functions in the Arduino code. HELP!!!!

**Comment by rlisle** [comment]
I apologize for being slow in getting all the pieces uploaded. I'm trying to clean things up a bit more first. Unfortunately I'm easily distracted. Fortunately, I think the help you're looking for is documented in [Alexa Particle Bridge](https://github.com/rlisle/alexaParticleBridge). You may also find some info posted on my [blog](https://ronlisle.com)

**Comment by rlisle** [comment]
I've created a new Patriot (a mashup of "Particle" and "IoT") repo that contains Arduino code. The source is available, and the library has been published on particle.io as "IoT".

**Comment by thomasfromla** [comment]
Thanks.



Thomas

-

Like robotics?

www.robots-and-androids.com<http://www.robots-and-androids.com>








On Apr 4, 2017, at 3:34 AM, Ron Lisle <notifications@github.com<mailto:notifications@github.com>> wrote:


I've created a new Patriot (a mashup of "Particle" and "IoT") repo that contains Arduino code. The source is available, and the library has been published on particle.io<http://particle.io> as "IoT".
